### ISSUE TITLE
Script Arguments not working as expected

### ISSUE THREAD

**Issue by glawrence** [ant-druha/PowerShell#10]
My .ps1 file starts as follows:

`param(
    [parameter(Mandatory=$true)]
    [String]$MyFileName
)`

Using an interactive PowerShell command line I can run `ParamTest.ps1 -MyFileName HelloWorld.txt` and everything is fine. However from within IntelliJ my configuration has "Script arguments: -MyFileName HelloWorld.txt" and I get an error message but looking at the command output in the output window showing what is run the - sign is getting removed, so this is why it fails.

**Comment by ant-druha** [comment]
Thanks for reporting!
